apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-deployment
  namespace: main-app
  annotations:
    linkerd.io/inject: enabled
  labels:
    app: web-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: ezyevent-web-ui
          image: gcr.io/ezyevents/web-ui:v2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
  namespace: main-app
  labels:
    app: web-ui
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 80
  selector:
    app: web-ui
  sessionAffinity: None
