apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-deployment
  labels:
    app: web-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
        - name: ezyevent-location-api
          image: gcr.io/ezyevents/web-ui:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
  labels:
    app: web-ui
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 80
  selector:
    app: web-ui
  sessionAffinity: None
